#!/usr/bin/env python3
import json
import re
import sys
from pathlib import Path

INPUT_KEYS = ["accent", "background", "card", "raised", "bars", "text", "mutedText", "separator"]
MODES = ["light", "dark"]
HEX_RE = re.compile(r"^[0-9A-Fa-f]{6}$")


def fail(path, message):
    label = str(path) if path else "catalog"
    raise SystemExit(f"{label}: {message}")


def c_string(value):
    parts = []
    for byte in value.encode("utf-8"):
        if byte == 0x5C:
            parts.append("\\\\")
        elif byte == 0x22:
            parts.append('\\"')
        elif 0x20 <= byte <= 0x7E:
            parts.append(chr(byte))
        else:
            parts.append(f"\\{byte:03o}")
    return '"' + "".join(parts) + '"'


def load_theme(path):
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        fail(path, f"invalid JSON: {exc}")

    slug = path.stem
    if data.get("schemaVersion") != 3:
        fail(path, "schemaVersion must be 3")
    if data.get("slug") != slug:
        fail(path, f"slug must match filename stem ({slug})")
    if not isinstance(data.get("name"), str) or not data["name"].strip():
        fail(path, "name must be a non-empty string")
    if data.get("variant") not in {"subtle", "balanced", "bold"}:
        fail(path, "variant must be subtle, balanced, or bold")
    if data.get("advancedEnabled") is not True:
        fail(path, "advancedEnabled must be true")

    input_obj = data.get("input")
    if not isinstance(input_obj, dict):
        fail(path, "input must be an object")
    for mode in MODES:
        mode_obj = input_obj.get(mode)
        if not isinstance(mode_obj, dict):
            fail(path, f"input.{mode} must be an object")
        for key in INPUT_KEYS:
            value = mode_obj.get(key)
            if not isinstance(value, str) or not HEX_RE.match(value):
                fail(path, f"input.{mode}.{key} must be exactly 6 hex digits")
            mode_obj[key] = value.upper()

    return {
        "slug": slug,
        "name": data["name"],
        "variant": data["variant"],
        "input": input_obj,
    }


def emit_header(path):
    path.write_text("""// Generated by theme-gallery/scripts/generate_catalog.py. Do not edit.
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

NSArray<NSString *> *ApolloThemeGalleryCatalogGeneratedSlugs(void);
NSDictionary *_Nullable ApolloThemeGalleryCatalogGeneratedThemeForSlug(NSString *slug);

NS_ASSUME_NONNULL_END
""")


def emit_implementation(path, themes):
    lines = [
        "// Generated by theme-gallery/scripts/generate_catalog.py. Do not edit.",
        "// Gallery slugs are persisted in user backups. Renaming a shipped slug",
        "// orphans restores on builds that no longer know the old slug.",
        '#import "ApolloThemeGalleryCatalog.gen.h"',
        '#import "ApolloThemeTokens.h"',
        "",
        "typedef struct {",
        "    const char *slug;",
        "    const char *name;",
        "    const char *variant;",
    ]
    for mode in MODES:
        for key in INPUT_KEYS:
            lines.append(f"    const char *{mode}_{key};")
    lines.extend([
        "} ApolloThemeGalleryEntry;",
        "",
        "static const ApolloThemeGalleryEntry kGalleryThemes[] = {",
    ])

    for theme in themes:
        values = [theme["slug"], theme["name"], theme["variant"]]
        for mode in MODES:
            for key in INPUT_KEYS:
                values.append(theme["input"][mode][key])
        encoded = ", ".join(c_string(value) for value in values)
        lines.append(f"    {{ {encoded} }},")

    lines.extend([
        "};",
        "",
        "static NSString *S(const char *value) { return [NSString stringWithUTF8String:value]; }",
        "",
        "NSArray<NSString *> *ApolloThemeGalleryCatalogGeneratedSlugs(void) {",
        "    static NSArray<NSString *> *slugs;",
        "    static dispatch_once_t once;",
        "    dispatch_once(&once, ^{",
        "        NSMutableArray<NSString *> *a = [NSMutableArray arrayWithCapacity:sizeof(kGalleryThemes) / sizeof(kGalleryThemes[0])];",
        "        for (NSUInteger i = 0; i < sizeof(kGalleryThemes) / sizeof(kGalleryThemes[0]); i++) {",
        "            [a addObject:S(kGalleryThemes[i].slug)];",
        "        }",
        "        slugs = [a copy];",
        "    });",
        "    return slugs;",
        "}",
        "",
        "static NSDictionary *ModeInput(const ApolloThemeGalleryEntry *e, BOOL dark) {",
        "    return @{",
    ])
    for key in INPUT_KEYS:
        field_light = f"light_{key}"
        field_dark = f"dark_{key}"
        lines.append(f"        @\"{key}\": S(dark ? e->{field_dark} : e->{field_light}),")
    lines.extend([
        "    };",
        "}",
        "",
        "static NSDictionary *ThemeDictionary(const ApolloThemeGalleryEntry *e) {",
        "    return @{",
        '        @"schemaVersion": @(kApolloThemeSchemaVersion),',
        '        @"name": S(e->name),',
        '        @"slug": S(e->slug),',
        '        @"variant": S(e->variant),',
        f"        kApolloThemeAdvancedOptionsEnabledKey: @YES,",
        '        @"input": @{ @"light": ModeInput(e, NO), @"dark": ModeInput(e, YES) },',
        "    };",
        "}",
        "",
        "NSDictionary *ApolloThemeGalleryCatalogGeneratedThemeForSlug(NSString *slug) {",
        "    if (slug.length == 0) return nil;",
        "    for (NSUInteger i = 0; i < sizeof(kGalleryThemes) / sizeof(kGalleryThemes[0]); i++) {",
        "        if ([slug isEqualToString:S(kGalleryThemes[i].slug)]) {",
        "            return ThemeDictionary(&kGalleryThemes[i]);",
        "        }",
        "    }",
        "    return nil;",
        "}",
        "",
    ])
    path.write_text("\n".join(lines))


def main(argv):
    if len(argv) != 4:
        raise SystemExit("usage: generate_catalog.py <themes-dir> <out-header> <out-impl>")
    themes_dir = Path(argv[1])
    out_header = Path(argv[2])
    out_impl = Path(argv[3])
    paths = sorted(themes_dir.glob("*.json"))
    if not paths:
        fail(themes_dir, "no theme JSON files found")
    themes = [load_theme(path) for path in paths]
    seen = set()
    for theme in themes:
        if theme["slug"] in seen:
            fail(None, f"duplicate slug {theme['slug']}")
        seen.add(theme["slug"])
    out_header.parent.mkdir(parents=True, exist_ok=True)
    out_impl.parent.mkdir(parents=True, exist_ok=True)
    emit_header(out_header)
    emit_implementation(out_impl, themes)
    print(f"generated {len(themes)} gallery themes")


if __name__ == "__main__":
    main(sys.argv)
